import MCMC.Finite.Convergence
import MCMC.PF.LinearAlgebra.Matrix.PerronFrobenius.ProjectiveMetric

/-!
# Finite stochastic matrices and Markov chains

This file packages Chapter 4 style statements on finite stochastic matrices on top of the existing
finite-state API from `MCMC.Finite.Core` and `MCMC.Finite.Convergence`.

In particular, it avoids duplicating the existing definition `MCMC.Finite.IsStationary`: the
row-vector convention is exposed through the equivalence `isStationary_iff_vecMul`.
-/

namespace MCMC.Finite

open Filter Matrix Topology

variable {n : Type*} [Fintype n] [DecidableEq n] [Nonempty n]

/-- A finite stochastic matrix is regular if it is primitive. -/
def IsRegular (P : Matrix n n ℝ) : Prop :=
  IsStochastic P ∧ Matrix.IsPrimitive P

/-- Column-vector and row-vector formulations of stationarity agree. -/
theorem isStationary_iff_vecMul
    {P : Matrix n n ℝ} {π : stdSimplex ℝ n} :
    IsStationary P π ↔ π.val ᵥ* P = π.val := by
  sorry

/--
Ergodic theorem for a primitive stochastic matrix: powers converge to the rank-one limit matrix
generated by the unique stationary distribution.
-/
theorem ergodic_theorem_for_primitive_stochastic
    {P : Matrix n n ℝ} (h_stoch : IsStochastic P) (h_prim : Matrix.IsPrimitive P) :
    ∃ π : stdSimplex ℝ n, IsStationary P π ∧
      Tendsto (fun k : ℕ => P ^ k) atTop (nhds (LimitMatrix π)) := by
  sorry

/--
Quantitative geometric convergence of the powers of a primitive stochastic matrix to equilibrium.
-/
theorem geometric_convergence_of_primitive_stochastic
    {P : Matrix n n ℝ} (h_stoch : IsStochastic P) (h_prim : Matrix.IsPrimitive P) :
    ∃ (π : stdSimplex ℝ n) (C ρ : ℝ),
      IsStationary P π ∧ 0 < C ∧ 0 ≤ ρ ∧ ρ < 1 ∧
      ∀ i j k, |(P ^ k) i j - π.val j| ≤ C * ρ ^ k := by
  sorry

/--
Scrambling gives strict contraction in total variation.
-/
theorem scrambling_implies_dobrushinCoeff_lt_one
    {P : Matrix n n ℝ} (h_stoch : IsStochastic P) (h_scrambling : P.IsScrambling) :
    Matrix.dobrushinCoeff P < 1 := by
  sorry

end MCMC.Finite
